### ISSUE TITLE
Investigate using more structured data for district roles file

### ISSUE THREAD

**Issue by genebean** [genebean/indiansprings-hugo#43]
From https://gohugo.io/templates/data-templates/#example-accessing-named-values-in-a-data-file

`<div>Short Description of {{.Site.Data.User0123.Name}}: <p>{{ index .Site.Data.User0123 "Short Description" | markdownify }}</p></div>`

⬆️ refers to an `index` function: https://gohugo.io/functions/index-function/

That function has examples that should allow allow for changing

```yaml
position1: ‘John Smith’
position2: ‘Jane Smith’
```

to something like this:

```yaml
vice_chair_foo:
  position_name: ‘Vice Chair of Foo’
  title: ‘Dr.’
  first_name: ‘John’
  last_name: ‘Smith’
  suffix: ‘III’
  nick_name: ‘Doc’
  pronoun: ‘he’
  direct_reports:
    - foo_a_chair:
         position_name: ‘Foo A Chair’
         title:
         first_name: ‘Janet’
         last_name: ‘Smith’
         suffix:
         nick_name: ‘Jane’
         pronoun: ‘she’
    - foo_b_chair:
         position_name: ‘Foo B Chair’
         title:
         first_name:
         last_name:
         suffix:
         nick_name:
         pronoun:
vice_chair_bar:
  position_name: ‘Vice Chair of Bar’
  title:
  first_name: ‘Jackson’
  last_name: ‘Smith’
  suffix:
  nick_name: ‘Jack
  pronoun: ‘he’
  direct_reports:
    - bar_a_chair:
         position_name: ‘Bar A Chair’
         title:
         first_name: ‘Betty’
         last_name: ‘Smith’
         suffix:
         nick_name:
         pronoun: ‘she’
    - bar_b_chair:
         position_name: ‘Bar B Chair’
         title:
         first_name:
         last_name:
         suffix:
         nick_name:
         pronoun:
```

Doing this codifies the organizational structure in the data and should make displaying that structure with mermaid much easier and less repetitive

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
